### PR TITLE
Fixed the deprecated call introduced in atom v0.196 + Add bootlint flag support

### PR DESCRIPTION
**Pull request by benjiro**
Changed init.coffee over to the new config schema (Old style has be deprecated)
Changed activationEvents to activationCommands (activationEvents has been deprecated)
Removed findFile include wasn't being used
Fixed disposable of right object when linter is destroyed

### CODE REVIEW

**Comment by benjiro** [comment]
Also add support for flags which was requested in #1 

The error/warning ids are from https://github.com/twbs/bootlint/wiki

**Comment by stramel** [comment]
:+1:

**Comment by kevinsawicki** [comment]
Thanks for this :anchor:

**Comment by kevinsawicki** [comment]
Published in 0.0.6

**Pull request merged**
