### PR TITLE
Rewrite linter

### LINKED ISSUE #9: Upcoming linter changes
We're in the process of replacing `linter` with a rewrite. Our central issue for tracking the plan is https://github.com/AtomLinter/linter-plus/issues/29. We're working hard to make this a smooth transition for you and for your users.

Please let us know here if you'd prefer to do the work yourself. If you have any questions or concerns please join us in our [room on gitter](https://gitter.im/AtomLinter/Linter).

### LINKED ISSUE #11: Object.activate is deprecated.
AtomLinter v0.X.Y API has been deprecated. Please refer to the Linter docs to update and the latest API: https://github.com/AtomLinter/Linter/wiki/Migrating-to-the-new-API     Object.activate  /Users/aevitas/.atom/packages/linter/lib/main.coffee:57:8  Package.activateNow  /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:240:19  unknown>  /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:221:30  Package.measure  /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:165:15  Package.activate  /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:213:14  PackageManager.activatePackage  /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:21

### PR DESCRIPTION
**Pull request by Arcanemagus**
This PR does the following:

- [X] Rewrite the linter in ES6
- [X] Add CI configs
- [X] Add linter configs
- [ ] Add specs

Fixes #9.
Fixes #11.

### CODE REVIEW

**Comment by Arcanemagus** [comment]
Will be implementing the specs hopefully later tonight, but figured I would throw this up here for comments.

**Comment by Arcanemagus** [comment]
AppVeyor is currently having queueing issues, it's passing locally on Windows and passing the other CI builds so I'm merging this.

**Comment by Arcanemagus** [comment]
For anyone interested, here was the test for the regex: https://regex101.com/r/fK7dR3/1

**Comment by steelbrain** [comment]
:+1:

**Pull request merged**
